# Generated by Django 5.0.1 on 2025-12-05 14:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'recovery_announcement',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MalamaContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('backup_email', models.EmailField(blank=True, max_length=254)),
                ('preferred_contact', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('both', 'Both')], default='email', max_length=20)),
                ('available_days', models.JSONField(default=list, help_text='Days of week available to host (e.g., ["monday", "wednesday"])')),
                ('max_meetings_per_week', models.IntegerField(default=2)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about Mālama availability')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('malama', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='malama_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mālama Contact',
                'verbose_name_plural': 'Mālama Contacts',
                'db_table': 'recovery_malamacontact',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Date of the meeting')),
                ('start_time', models.TimeField(default='23:00:00', help_text='Meeting start time (default 11pm PT)')),
                ('end_time', models.TimeField(default='03:00:00', help_text='Meeting end time (default 3am PT)')),
                ('zoom_link', models.URLField(blank=True, help_text='Zoom meeting URL', max_length=500)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=50)),
                ('zoom_passcode', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('theme', models.CharField(blank=True, help_text='Optional meeting theme or topic', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for hosts')),
                ('attendee_count', models.IntegerField(default=0, help_text='Number of attendees')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(blank=True, help_text='Mālama (crew member) hosting this meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'db_table': 'recovery_meeting',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='recovery.meeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Attendance',
                'verbose_name_plural': 'Meeting Attendances',
                'db_table': 'recovery_meetingattendance',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSignUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional note from Mālama')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('malama', models.ForeignKey(help_text='Mālama signing up to host', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_signups', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Sign-Up',
                'verbose_name_plural': 'Meeting Sign-Ups',
                'db_table': 'recovery_meetingsignup',
                'ordering': ['requested_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['date', 'status'], name='recovery_me_date_e748d5_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['host'], name='recovery_me_host_id_b46ec5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['meeting'], name='recovery_me_meeting_0415bb_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['user'], name='recovery_me_user_id_1b267d_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingsignup',
            index=models.Index(fields=['malama', 'status'], name='recovery_me_malama__70baff_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingsignup',
            index=models.Index(fields=['requested_date', 'status'], name='recovery_me_request_fbfca6_idx'),
        ),
    ]
