# Generated by Django 5.0.1 on 2025-12-01 00:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('public_handle', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('pronouns', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('recovery_affiliations', models.JSONField(blank=True, default=list, help_text='e.g., ["AA", "NA", "SMART", "Non-traditional"]')),
                ('privacy_settings', models.JSONField(blank=True, default=dict, help_text='User privacy preferences for profile, journals, messaging, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users_customuser',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('my_story', models.TextField(blank=True, help_text='Longer personal recovery story')),
                ('my_story_visibility', models.CharField(choices=[('private', 'Private'), ('friends', 'Friends Only'), ('community', 'Community'), ('public', 'Public')], default='private', max_length=20)),
                ('show_sobriety_counter', models.BooleanField(default=False)),
                ('show_affiliations', models.BooleanField(default=False)),
                ('show_location', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'users_profile',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('guide', 'Guide'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('guest', 'Guest')], max_length=20)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('group', 'Group'), ('meeting', 'Meeting')], default='global', max_length=20)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'users_role',
            },
        ),
        migrations.CreateModel(
            name='SobrietyDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('substance', models.CharField(help_text='e.g., alcohol, opioids, all substances, custom', max_length=100)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('restart_count', models.IntegerField(default=0)),
                ('previous_start_date', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('friends', 'Friends Only'), ('community', 'Community'), ('public', 'Public')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobriety_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sobriety Date',
                'verbose_name_plural': 'Sobriety Dates',
                'db_table': 'users_sobrietydate',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['public_handle'], name='users_custo_public__21835f_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='users_custo_created_f4b145_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['user', 'role'], name='users_role_user_id_5bf6cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('user', 'role', 'scope_type', 'scope_id')},
        ),
        migrations.AddIndex(
            model_name='sobrietydate',
            index=models.Index(fields=['user', 'is_active'], name='users_sobri_user_id_1ce8d2_idx'),
        ),
    ]
